
version: '3'
services:
  web:
    build: ./app
    ports:
      - "5000:5000"
  zap:
    image: ghcr.io/zaproxy/zaproxy:latest
    entrypoint: zap.sh
    command: ["-cmd", "-quickurl", "http://web:5000", "-quickout", "/zap/reports/report.html"]
    volumes:
      - ./zap_reports:/zap/reports

