name: DAST Scan with OWASP ZAP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dast-scan:
    runs-on: ubuntu-latest

    services:
      web:
        build:
          context: ./app
        ports:
          - 5000:5000
        options: >-
          --health-cmd="curl --fail http://localhost:5000 || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Wait for web to be healthy
      run: |
        echo "Waiting for the app to start..."
        sleep 15

    - name: Run ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://localhost:5000'
        cmd_options: '-I -r report.html'

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v3
      with:
        name: zap-report
        path: report.html
