name: DAST Scan with OWASP ZAP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dast-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: |
        docker-compose up -d
        echo "Waiting for the app to be ready..."
        sleep 20

    - name: Run OWASP ZAP baseline scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://localhost:5000'
        cmd_options: '-I -r report.html'

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v3
      with:
        name: zap-report
        path: report.html
